export const VERSION = '0.2.0';

export * from './analysis/index.js';
export * from './corpus/index.js';
export * from './geometry/distance.js';
export * from './geometry/presets.js';
export * from './geometry/types.js';
export * from './host/locale.js';
export * from './layout/compile.js';
export * from './layout/json.js';
export * from './layout/ops.js';
export * from './layout/schema.js';
export * from './layout/text.js';
export * from './layout/types.js';
export * from './layouts/index.js';
export * from './rules/index.js';
export * from './sim/machine.js';
export * from './sim/producers.js';
export * from './sim/resolver.js';
export * from './storage/ids.js';
export * from './tables/tables.js';
