import {
  type AdaptiveTrigger,
  type CompiledLayout,
  GEOMETRY_PRESET_IDS,
  type Layout,
  type LayoutFeatures,
  type Mod,
  tapLabel,
  toCanonicalJson,
} from '@layoutmaster/core';
import { type Dispatch, useEffect, useState } from 'react';
import type { ProducerDTO } from '../../engine/protocol.js';
import {
  type BindingFields,
  bindingFromFields,
  EDITABLE_KINDS,
  emptyMacroStep,
  fieldsFromBinding,
  MACRO_STEP_KINDS,
  type MacroStep,
} from './binding-form.js';
import { type BindingTextContext, bindingText, parseBindingText } from './binding-text.js';
import type { EditAction, EditState } from './reducer.js';
import { MODS } from './reducer.js';

type Send = Dispatch<EditAction>;

interface PanelProps {
  state: EditState;
  send: Send;
}

/** Key: what the selected key does, and how to change it. */
export function BindingPanel({ state, send }: PanelProps) {
  const { compiled, selected, layer } = state;
  const pos = selected ? compiled.keyIndex.get(selected) : undefined;
  const current = pos === undefined ? undefined : compiled.layers[layer].bindings[pos];
  const [fields, setFields] = useState<BindingFields>(() => fieldsFromBinding(current));
  const [replacing, setReplacing] = useState(false);

  // Selecting another key starts the form from that key's binding.
  useEffect(() => {
    setFields(fieldsFromBinding(current));
    setReplacing(false);
  }, [current]);

  // This form is built from `BindingFields`, which has no room for an adaptive key's branches or a
  // hold-tap's arms: applying it to one would quietly throw them away. A binding a feature
  // generated has the opposite problem — it is rewritten on the next compile, so an edit here
  // would look as though it did nothing.
  const written = bindingText(compiled, current);
  const owner =
    selected === null
      ? undefined
      : compiled.featureOwned.get(compiled.layers[layer].id)?.get(selected);
  const locked = owner !== undefined || (!written.exact && !replacing);

  if (!selected) return <p className="text-sm opacity-70">Select a key on the keyboard.</p>;

  const set = (patch: Partial<BindingFields>) => setFields((f) => ({ ...f, ...patch }));

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center gap-2">
        <span className="badge badge-neutral font-mono">{selected}</span>
        <span className="text-xs opacity-70">
          layer {compiled.layers[layer].name} · current{' '}
          {current ? tapLabel(compiled, current) || '·' : '·'}
        </span>
        <button
          type="button"
          className="btn btn-xs"
          onClick={() => send({ type: state.swapFrom ? 'cancelSwap' : 'startSwap' })}
        >
          {state.swapFrom ? 'click target key…' : 'swap with…'}
        </button>
        <button
          type="button"
          className="btn btn-xs btn-ghost"
          // Clearing a key a feature owns only lasts until the next compile, which regenerates it.
          disabled={owner !== undefined}
          onClick={() => send({ type: 'clearBinding' })}
        >
          clear
        </button>
      </div>

      {owner !== undefined ? (
        <div className="alert alert-warning py-2 text-xs">
          <span>
            Generated by the <span className="font-mono">{owner}</span> feature, and rewritten
            whenever the layout compiles. Turn that feature off in Features to edit this key.
          </span>
        </div>
      ) : (
        !written.exact && (
          <div className="alert alert-warning py-2 text-xs flex-wrap gap-2">
            <span>
              <span className="font-mono">{written.text}</span> is {written.why}. This form cannot
              hold that, so applying it would replace the binding rather than change it.
            </span>
            {!replacing && (
              <button type="button" className="btn btn-xs" onClick={() => setReplacing(true)}>
                Replace anyway
              </button>
            )}
          </div>
        )
      )}

      <form
        onSubmit={(e) => {
          e.preventDefault();
          // Belt and braces: the controls are already disabled, and a submit cannot reach here.
          if (locked) return;
          send({ type: 'setBinding', binding: bindingFromFields(fields) });
        }}
      >
        <fieldset
          className={`grid grid-cols-2 gap-2 ${locked ? 'opacity-50' : ''}`}
          disabled={locked}
        >
          <label className="form-control">
            <span className="label-text text-xs">Kind</span>
            <select
              aria-label="Binding kind"
              className="select select-sm select-bordered"
              value={fields.kind}
              onChange={(e) => set({ kind: e.target.value as BindingFields['kind'] })}
            >
              {EDITABLE_KINDS.map((k) => (
                <option key={k} value={k}>
                  {k}
                </option>
              ))}
            </select>
          </label>

          <label className="form-control">
            <span className="label-text text-xs">Symbol / macro text</span>
            <input
              aria-label="Symbol"
              className="input input-sm input-bordered font-mono"
              value={fields.symbol}
              onChange={(e) => set({ symbol: e.target.value })}
            />
          </label>

          <label className="form-control">
            <span className="label-text text-xs">Shifted symbol</span>
            <input
              aria-label="Shifted symbol"
              className="input input-sm input-bordered font-mono"
              value={fields.shifted}
              onChange={(e) => set({ shifted: e.target.value })}
            />
          </label>

          <label className="form-control">
            <span className="label-text text-xs">Layer</span>
            <select
              aria-label="Layer for this binding"
              className="select select-sm select-bordered"
              value={fields.layer}
              onChange={(e) => set({ layer: e.target.value })}
            >
              <option value="">—</option>
              {compiled.layers.map((l) => (
                <option key={l.id} value={l.id}>
                  {l.name}
                </option>
              ))}
            </select>
          </label>

          <label className="form-control">
            <span className="label-text text-xs">Arm layer after macro</span>
            <select
              aria-label="Layer armed after the macro"
              className="select select-sm select-bordered"
              value={fields.thenLayer}
              onChange={(e) => set({ thenLayer: e.target.value })}
            >
              <option value="">—</option>
              {compiled.layers.map((l) => (
                <option key={l.id} value={l.id}>
                  {l.name}
                </option>
              ))}
            </select>
          </label>

          <label className="form-control">
            <span className="label-text text-xs">Modifier</span>
            <select
              aria-label="Modifier"
              className="select select-sm select-bordered"
              value={fields.mod}
              onChange={(e) => set({ mod: e.target.value as BindingFields['mod'] })}
            >
              {MODS.map((m) => (
                <option key={m} value={m}>
                  {m}
                </option>
              ))}
            </select>
          </label>

          <label className="form-control col-span-2">
            <span className="label-text text-xs">Behavior reference</span>
            <select
              aria-label="Behavior"
              className="select select-sm select-bordered"
              value={fields.ref}
              onChange={(e) => set({ ref: e.target.value })}
            >
              <option value="">—</option>
              {Object.keys(state.layout.behaviors ?? {}).map((name) => (
                <option key={name} value={name}>
                  {name}
                </option>
              ))}
            </select>
          </label>

          <label className="form-control col-span-2">
            <span className="label-text text-xs">Tag (adaptive branches can match on it)</span>
            <input
              aria-label="Binding tag"
              className="input input-sm input-bordered font-mono"
              value={fields.tag}
              onChange={(e) => set({ tag: e.target.value })}
            />
          </label>

          {fields.kind === 'macro' ? (
            <div className="col-span-2">
              <MacroStepsEditor
                state={state}
                steps={fields.macroSteps}
                onChange={(macroSteps) => set({ macroSteps })}
              />
            </div>
          ) : null}

          <button type="submit" className="btn btn-sm btn-primary col-span-2">
            Apply to {selected}
          </button>
        </fieldset>
      </form>
    </div>
  );
}

/** Layers: rename, pair with a shifted twin, add and remove. */
/**
 * Steps of a macro, in order. A macro that only types text keeps the compact `symbols` shape; add a
 * step and it becomes an explicit list, which is what lets one key type text *and* arm a layer or a
 * modifier.
 */
function MacroStepsEditor({
  state,
  steps,
  onChange,
}: {
  state: EditState;
  steps: MacroStep[];
  onChange: (steps: MacroStep[]) => void;
}) {
  const replace = (i: number, step: MacroStep) =>
    onChange(steps.map((s, j) => (j === i ? step : s)));
  const move = (i: number, by: number) => {
    const next = [...steps];
    const target = i + by;
    if (target < 0 || target >= next.length) return;
    [next[i], next[target]] = [next[target], next[i]];
    onChange(next);
  };

  return (
    <fieldset className="rounded border border-base-300 p-2">
      <legend className="px-1 text-xs opacity-70">Macro steps</legend>
      {steps.length === 0 ? (
        <p className="text-[11px] opacity-60">
          None — the macro types the text above. Add a step to build a sequence instead.
        </p>
      ) : null}
      <ul className="space-y-1">
        {steps.map((step, i) => (
          <li key={step.id} className="flex items-center gap-1">
            <select
              aria-label={`Step ${i + 1} kind`}
              className="select select-xs select-bordered"
              value={step.kind}
              onChange={(e) =>
                replace(i, {
                  ...emptyMacroStep(e.target.value as MacroStep['kind']),
                  id: step.id,
                })
              }
            >
              {MACRO_STEP_KINDS.map((k) => (
                <option key={k} value={k}>
                  {k === 'text'
                    ? 'type text'
                    : k === 'sl'
                      ? 'arm layer'
                      : k === 'sk'
                        ? 'arm modifier'
                        : 'run behavior'}
                </option>
              ))}
            </select>
            {step.kind === 'text' ? (
              <input
                aria-label={`Step ${i + 1} text`}
                className="input input-xs input-bordered font-mono flex-1"
                value={step.text}
                onChange={(e) => replace(i, { id: step.id, kind: 'text', text: e.target.value })}
              />
            ) : null}
            {step.kind === 'sl' ? (
              <select
                aria-label={`Step ${i + 1} layer`}
                className="select select-xs select-bordered flex-1"
                value={step.layer}
                onChange={(e) => replace(i, { id: step.id, kind: 'sl', layer: e.target.value })}
              >
                <option value="">—</option>
                {state.compiled.layers.map((l) => (
                  <option key={l.id} value={l.id}>
                    {l.name}
                  </option>
                ))}
              </select>
            ) : null}
            {step.kind === 'sk' ? (
              <select
                aria-label={`Step ${i + 1} modifier`}
                className="select select-xs select-bordered flex-1"
                value={step.mod}
                onChange={(e) =>
                  replace(i, { id: step.id, kind: 'sk', mod: e.target.value as Mod })
                }
              >
                {MODS.map((m) => (
                  <option key={m} value={m}>
                    {m}
                  </option>
                ))}
              </select>
            ) : null}
            {step.kind === 'ref' ? (
              <select
                aria-label={`Step ${i + 1} behavior`}
                className="select select-xs select-bordered flex-1"
                value={step.ref}
                onChange={(e) => replace(i, { id: step.id, kind: 'ref', ref: e.target.value })}
              >
                <option value="">—</option>
                {Object.keys(state.layout.behaviors ?? {}).map((name) => (
                  <option key={name} value={name}>
                    {name}
                  </option>
                ))}
              </select>
            ) : null}
            <button
              type="button"
              aria-label={`Move step ${i + 1} up`}
              className="btn btn-ghost btn-xs"
              onClick={() => move(i, -1)}
            >
              ↑
            </button>
            <button
              type="button"
              aria-label={`Remove step ${i + 1}`}
              className="btn btn-ghost btn-xs"
              onClick={() => onChange(steps.filter((_, j) => j !== i))}
            >
              ✕
            </button>
          </li>
        ))}
      </ul>
      <button
        type="button"
        className="btn btn-xs mt-1"
        onClick={() => onChange([...steps, emptyMacroStep('text')])}
      >
        Add step
      </button>
    </fieldset>
  );
}

/** A trigger's condition, as the panel shows it: symbols, tags, or both. */
function triggerCondition(t: AdaptiveTrigger): string {
  const parts: string[] = [];
  if (t.afterAny?.length) parts.push(t.afterAny.join(' '));
  if (t.afterTags?.length) parts.push(`from ${t.afterTags.join(' ')}`);
  return parts.join(' · ') || 'always';
}

function FeatureRow({
  title,
  hint,
  on,
  onToggle,
  children,
}: {
  title: string;
  hint: string;
  on: boolean;
  onToggle: (next: boolean) => void;
  children?: React.ReactNode;
}) {
  return (
    <div className="rounded border border-base-300 p-3">
      <label className="flex items-start gap-2">
        <input
          type="checkbox"
          aria-label={title}
          className="toggle toggle-sm mt-0.5"
          checked={on}
          onChange={(e) => onToggle(e.target.checked)}
        />
        <span>
          <span className="font-medium text-sm">{title}</span>
          <span className="block text-[11px] opacity-70">{hint}</span>
        </span>
      </label>
      {on && children ? <div className="mt-2 pl-8">{children}</div> : null}
    </div>
  );
}

/**
 * Features: the typing behaviours a keymap would otherwise need extra layers for.
 *
 * Everything here compiles down to ordinary bindings, so the layer list stays the set of layers a
 * typist actually reaches. The trigger tables are shown read-only — a trigger can hold any binding,
 * and the JSON panel is the honest place to edit one.
 */
export function FeaturesPanel({ state, send }: PanelProps) {
  const f: LayoutFeatures = state.layout.features ?? {};
  const set = (next: LayoutFeatures) => send({ type: 'setFeatures', features: next });
  const enabled = (v: { enabled?: boolean } | undefined) => v !== undefined && v.enabled !== false;

  return (
    <div className="space-y-3">
      <p className="text-[11px] opacity-70">
        Firmware needs a pre-shifted copy of a layer, or a one-shot layer armed by a macro, to do
        these. Declared here they are what they are, and the layer list stays honest.
      </p>

      <FeatureRow
        title="Sentence case"
        hint="Capitalise the first letter after sentence-ending punctuation."
        on={enabled(f.sentenceCase)}
        onToggle={(on) => set({ ...f, sentenceCase: on ? {} : undefined })}
      >
        <label className="form-control">
          <span className="label-text text-xs">Ends a sentence</span>
          <input
            aria-label="Sentence-ending punctuation"
            className="input input-xs input-bordered w-40 font-mono"
            value={(f.sentenceCase?.after ?? ['.', '?', '!']).join(' ')}
            onChange={(e) =>
              set({
                ...f,
                sentenceCase: {
                  ...f.sentenceCase,
                  after: e.target.value.split(/\s+/).filter(Boolean),
                },
              })
            }
          />
        </label>
      </FeatureRow>

      <FeatureRow
        title="Caps word"
        hint="Hold shift for the rest of the word, from the shift key."
        on={enabled(f.capsWord)}
        onToggle={(on) => set({ ...f, capsWord: on ? {} : undefined })}
      >
        <label className="form-control">
          <span className="label-text text-xs">Does not end the word</span>
          <input
            aria-label="Caps word continue list"
            className="input input-xs input-bordered w-40 font-mono"
            value={(f.capsWord?.continueList ?? []).join(' ')}
            onChange={(e) =>
              set({
                ...f,
                capsWord: {
                  ...f.capsWord,
                  continueList: e.target.value.split(/\s+/).filter(Boolean),
                },
              })
            }
          />
        </label>
      </FeatureRow>

      <FeatureRow
        title="Alt repeat"
        hint="A repeat key whose output depends on the previous press."
        on={enabled(f.altRepeat)}
        onToggle={(on) =>
          set({ ...f, altRepeat: on ? (f.altRepeat ?? { triggers: [] }) : undefined })
        }
      >
        {f.altRepeat ? (
          <TriggerTable
            compiled={state.compiled}
            label="Alt repeat"
            rows={[
              ...f.altRepeat.triggers,
              ...(f.altRepeat.secondStage?.triggers ?? []).map((t) => ({
                ...t,
                afterTags: f.altRepeat?.secondStage?.afterTags,
              })),
            ]}
          />
        ) : null}
      </FeatureRow>

      {(f.adaptiveKeys ?? []).map((a, i) => (
        <FeatureRow
          key={a.id}
          title={a.label ?? a.id}
          hint={`Adaptive key on ${(a.at ?? []).map((p) => `${p.layer}/${p.key}`).join(', ') || 'no key'}.`}
          on={a.enabled !== false}
          onToggle={(on) => {
            const keys = [...(f.adaptiveKeys ?? [])];
            keys[i] = { ...a, enabled: on };
            set({ ...f, adaptiveKeys: keys });
          }}
        >
          <TriggerTable compiled={state.compiled} label={a.label ?? a.id} rows={a.triggers} />
        </FeatureRow>
      ))}
    </div>
  );
}

function TriggerTable({
  compiled,
  label,
  rows,
}: {
  compiled: CompiledLayout;
  label: string;
  rows: AdaptiveTrigger[];
}) {
  if (rows.length === 0) return <p className="text-[11px] opacity-60">No triggers.</p>;
  return (
    <table className="table table-xs" aria-label={`${label} triggers`}>
      <thead>
        <tr>
          <th>After</th>
          <th>Types</th>
        </tr>
      </thead>
      <tbody>
        {rows.map((t) => (
          <tr key={`${triggerCondition(t)}\u2192${tapLabel(compiled, t.binding)}`}>
            <td className="font-mono">{triggerCondition(t)}</td>
            <td className="font-mono">{tapLabel(compiled, t.binding)}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export function LayersPanel({ state, send }: PanelProps) {
  const [newLayer, setNewLayer] = useState('');
  return (
    <div className="space-y-2">
      {state.layout.layers.map((layer) => (
        <div key={layer.id} className="flex flex-wrap items-center gap-2">
          <input
            aria-label={`Name of layer ${layer.id}`}
            className="input input-xs input-bordered w-32"
            value={layer.name}
            onChange={(e) => send({ type: 'renameLayer', id: layer.id, name: e.target.value })}
          />
          <span className="font-mono text-xs opacity-60 w-20 truncate">{layer.id}</span>
          <button
            type="button"
            className="btn btn-ghost btn-xs"
            onClick={() => {
              if (window.confirm('Remove this layer?')) send({ type: 'removeLayer', id: layer.id });
            }}
          >
            ✕
          </button>
        </div>
      ))}

      <form
        className="flex gap-2"
        onSubmit={(e) => {
          e.preventDefault();
          send({ type: 'addLayer', name: newLayer });
          setNewLayer('');
        }}
      >
        <input
          aria-label="New layer name"
          placeholder="new layer"
          className="input input-xs input-bordered flex-1"
          value={newLayer}
          onChange={(e) => setNewLayer(e.target.value)}
        />
        <button type="submit" className="btn btn-xs">
          + layer
        </button>
      </form>
    </div>
  );
}

/** Geometry and the keys with a special role. */
export function GeometryPanel({ state, send }: PanelProps) {
  const { layout, compiled } = state;
  const preset = 'preset' in layout.geometry ? layout.geometry.preset : 'custom';
  return (
    <div className="space-y-3">
      <label className="form-control">
        <span className="label-text text-xs">Preset</span>
        <select
          aria-label="Geometry preset"
          className="select select-sm select-bordered"
          value={preset}
          disabled
        >
          {GEOMETRY_PRESET_IDS.map((id) => (
            <option key={id} value={id}>
              {id}
            </option>
          ))}
          {preset === 'custom' && <option value="custom">custom</option>}
        </select>
        <span className="text-[11px] opacity-60">
          Changing geometry moves every key, so it is done from the import in the library.
        </span>
      </label>

      <label className="form-control">
        <span className="label-text text-xs">Space key</span>
        <select
          aria-label="Space key"
          className="select select-sm select-bordered"
          value={layout.keys.space}
          onChange={(e) => send({ type: 'setKeys', space: e.target.value })}
        >
          {compiled.keys.map((k) => (
            <option key={k.id} value={k.id}>
              {k.id}
            </option>
          ))}
        </select>
      </label>

      <label className="form-control">
        <span className="label-text text-xs">Shift key</span>
        <select
          aria-label="Shift key"
          className="select select-sm select-bordered"
          value={layout.keys.shift?.key ?? ''}
          onChange={(e) => send({ type: 'setKeys', shift: e.target.value || null })}
        >
          <option value="">—</option>
          {compiled.keys.map((k) => (
            <option key={k.id} value={k.id}>
              {k.id}
            </option>
          ))}
        </select>
      </label>

      <label className="form-control">
        <span className="label-text text-xs">Shift kind</span>
        <select
          aria-label="Shift kind"
          className="select select-sm select-bordered"
          value={layout.keys.shift?.kind ?? 'sk'}
          onChange={(e) => send({ type: 'setKeys', shiftKind: e.target.value as 'sk' | 'hold' })}
        >
          <option value="sk">sticky (one-shot)</option>
          <option value="hold">hold</option>
        </select>
      </label>

      <label className="form-control">
        <span className="label-text text-xs">Doubled letters</span>
        <select
          aria-label="Doubled letters"
          className="select select-sm select-bordered"
          value={layout.repeatPolicy?.doubledLetters ?? 'repeatKey'}
          onChange={(e) =>
            send({ type: 'setKeys', repeat: e.target.value as 'repeatKey' | 'tapTwice' })
          }
        >
          <option value="repeatKey">repeat key</option>
          <option value="tapTwice">tap twice</option>
        </select>
      </label>
    </div>
  );
}

/** Combos: chords that produce a symbol or a command. */
export function CombosPanel({ state, send }: PanelProps) {
  const [keys, setKeys] = useState('');
  const [output, setOutput] = useState('');
  const [role, setRole] = useState<'typing' | 'command'>('typing');
  const [error, setError] = useState<string | null>(null);
  const combos = state.layout.combos ?? [];
  const layerName = state.compiled.layers[state.layer].name;
  const picking = state.comboPick !== null;
  // While picking, the keys come off the board; otherwise they are typed as ids.
  const chosen = picking ? (state.comboPick ?? []) : [];

  const context: BindingTextContext = {
    layers: state.compiled.layers.map((l) => ({ id: l.id, name: l.name })),
    behaviors: Object.keys(state.layout.behaviors ?? {}),
    hostLocale: state.compiled.hostLocale,
  };

  return (
    <div className="space-y-3">
      <section
        className="overflow-x-auto"
        // biome-ignore lint/a11y/noNoninteractiveTabindex: a scrollable region must be reachable by keyboard.
        tabIndex={0}
        aria-label="Combos"
      >
        <table className="table table-xs">
          <thead>
            <tr>
              <th>Keys</th>
              <th>Output</th>
              <th>Layers</th>
              <th>Role</th>
              <th />
            </tr>
          </thead>
          <tbody>
            {combos.map((c) => (
              <tr key={c.id}>
                <td className="font-mono">
                  <button
                    type="button"
                    className="link link-hover"
                    aria-label={`Show the keys of ${c.keys.join('+')}`}
                    onClick={() =>
                      send({
                        type: 'setBoardHighlight',
                        keys: state.boardHighlight.length > 0 ? [] : c.keys,
                      })
                    }
                  >
                    {c.keys.join('+')}
                  </button>
                </td>
                <td className="font-mono">{tapLabel(state.compiled, c.binding)}</td>
                <td className="text-xs opacity-70">{(c.layers ?? []).join(', ') || 'all'}</td>
                <td>
                  <button
                    type="button"
                    className={`badge badge-xs ${c.role === 'typing' ? 'badge-primary' : ''}`}
                    onClick={() => send({ type: 'toggleComboRole', id: c.id as string })}
                  >
                    {c.role}
                  </button>
                </td>
                <td>
                  <button
                    type="button"
                    className="btn btn-ghost btn-xs"
                    onClick={() => send({ type: 'removeCombo', id: c.id as string })}
                  >
                    ✕
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <form
        className="flex flex-wrap items-center gap-2"
        onSubmit={(e) => {
          e.preventDefault();
          const chosenKeys = picking
            ? chosen
            : keys
                .split(/[\s,+]+/)
                .filter(Boolean)
                .map((k) => k.toUpperCase());
          const binding = parseBindingText(output, context);
          if (!binding.ok) {
            setError(binding.error);
            return;
          }
          setError(null);
          send({
            type: 'addCombo',
            keys: chosenKeys,
            binding: bindingFromFields(binding.fields),
            role,
          });
          setKeys('');
          setOutput('');
        }}
      >
        <button
          type="button"
          className={`btn btn-xs ${picking ? 'btn-primary' : ''}`}
          onClick={() => send({ type: picking ? 'comboPickCancel' : 'comboPickStart' })}
        >
          {picking ? 'picking on board…' : 'pick on board'}
        </button>
        {picking ? (
          <output className="font-mono text-xs" aria-label="Combo keys picked">
            {chosen.length > 0 ? chosen.join('+') : 'click the keys'}
          </output>
        ) : (
          <input
            aria-label="Combo keys"
            placeholder="Keys (e.g. LHR+LHM)"
            className="input input-xs input-bordered font-mono"
            value={keys}
            onChange={(e) => setKeys(e.target.value)}
          />
        )}
        <input
          aria-label="Combo output"
          placeholder="Output (e.g. q, &macro ão)"
          className="input input-xs input-bordered font-mono w-36"
          value={output}
          onChange={(e) => {
            setOutput(e.target.value);
            setError(null);
          }}
        />
        <select
          aria-label="Combo role"
          className="select select-xs select-bordered"
          value={role}
          onChange={(e) => setRole(e.target.value as 'typing' | 'command')}
        >
          <option value="typing">typing</option>
          <option value="command">command</option>
        </select>
        <button type="submit" className="btn btn-xs">
          Add combo on {layerName}
        </button>
      </form>
      {error && <p className="text-error text-xs">{error}</p>}
      <p className="text-[11px] opacity-60">
        Only combos with the typing role are offered to the simulator as a way to produce a symbol.
      </p>
    </div>
  );
}

/** Behaviors: the named bindings that keys refer to. */
export function BehaviorsPanel({ state, send }: PanelProps) {
  return (
    <form
      className="space-y-2"
      onSubmit={(e) => {
        e.preventDefault();
        send({ type: 'behaviorsApply', json: state.behaviorsJson });
      }}
    >
      <p className="text-xs opacity-70">
        Named bindings such as adaptive keys and mod-morphs. Keys reach them with a reference.
      </p>
      <textarea
        aria-label="Behaviors"
        rows={14}
        className="textarea textarea-bordered w-full font-mono text-xs"
        value={state.behaviorsJson}
        onChange={(e) => send({ type: 'behaviorsChange', json: e.target.value })}
      />
      {state.behaviorsError && <p className="text-error text-xs">{state.behaviorsError}</p>}
      <button type="submit" className="btn btn-sm">
        Apply behaviors
      </button>
    </form>
  );
}

/** Typing paths: which producer wins when a symbol can be typed more than one way. */
export function PathsPanel({
  state,
  send,
  producers,
}: PanelProps & { producers: Record<string, ProducerDTO[]> }) {
  // Which chip is in flight, as `symbol:index`, so a drag cannot cross from one symbol to another.
  const [dragging, setDragging] = useState<string | null>(null);

  const multi = Object.entries(producers)
    .filter(([symbol, list]) => symbol !== '' && list.length > 1)
    .sort(([a], [b]) => a.localeCompare(b));

  if (multi.length === 0) {
    return <p className="text-sm opacity-70">Every symbol has a single producer.</p>;
  }

  const pathsFor = (symbol: string) => {
    const declared = state.layout.typingPaths?.[symbol];
    if (declared && declared.length > 0) return declared;
    return (producers[symbol] ?? []).map((p) => ({ producer: p.id, enabled: true }));
  };

  /** Send the whole list back, with one entry moved from `from` to `to`. */
  const reorder = (symbol: string, from: number, to: number) => {
    const entries = [...pathsFor(symbol)];
    if (from === to || to < 0 || to >= entries.length) return;
    const [moved] = entries.splice(from, 1);
    entries.splice(to, 0, moved);
    send({ type: 'pathSet', symbol, entries });
  };

  const toggle = (symbol: string, producer: string) => {
    send({
      type: 'pathSet',
      symbol,
      entries: pathsFor(symbol).map((e) =>
        e.producer === producer ? { ...e, enabled: !(e.enabled ?? true) } : e,
      ),
    });
  };

  return (
    <div className="space-y-3">
      <p className="text-[11px] opacity-60">
        The order is the order the simulator tries. Drag an alternative to move it, or use the
        arrows.
      </p>
      {multi.map(([symbol]) => (
        <div key={symbol} className="space-y-1">
          <h3 className="font-mono text-sm">{symbol === ' ' ? '␣' : symbol}</h3>
          <ol className="space-y-1">
            {pathsFor(symbol).map((entry, i, all) => {
              const meta = producers[symbol]?.find((p) => p.id === entry.producer);
              const enabled = entry.enabled ?? true;
              return (
                <li
                  key={entry.producer}
                  draggable
                  onDragStart={(e) => {
                    e.dataTransfer.setData('text/plain', String(i));
                    e.dataTransfer.effectAllowed = 'move';
                    setDragging(`${symbol}:${i}`);
                  }}
                  onDragEnd={() => setDragging(null)}
                  onDragOver={(e) => {
                    if (dragging?.startsWith(`${symbol}:`)) e.preventDefault();
                  }}
                  onDrop={(e) => {
                    e.preventDefault();
                    const from = Number(e.dataTransfer.getData('text/plain'));
                    setDragging(null);
                    if (Number.isInteger(from)) reorder(symbol, from, i);
                  }}
                  className={`flex items-center gap-2 text-xs rounded px-1 cursor-grab border border-transparent hover:border-base-300 ${
                    enabled ? '' : 'opacity-40'
                  } ${dragging === `${symbol}:${i}` ? 'opacity-50' : ''}`}
                >
                  <span aria-hidden="true" className="opacity-40">
                    ⠿
                  </span>
                  <input
                    type="checkbox"
                    className="checkbox checkbox-xs"
                    aria-label={`Use ${entry.producer}`}
                    checked={enabled}
                    onChange={() => toggle(symbol, entry.producer)}
                  />
                  <span className="font-mono flex-1 truncate">
                    {meta
                      ? `${meta.kind} · ${entry.producer} · ${meta.cost} presses`
                      : entry.producer}
                  </span>
                  <button
                    type="button"
                    className="btn btn-ghost btn-xs"
                    aria-label={`Move ${entry.producer} up`}
                    disabled={i === 0}
                    onClick={() => reorder(symbol, i, i - 1)}
                  >
                    ↑
                  </button>
                  <button
                    type="button"
                    className="btn btn-ghost btn-xs"
                    aria-label={`Move ${entry.producer} down`}
                    disabled={i === all.length - 1}
                    onClick={() => reorder(symbol, i, i + 1)}
                  >
                    ↓
                  </button>
                </li>
              );
            })}
          </ol>
        </div>
      ))}
    </div>
  );
}

/** JSON: the document itself, for reading and for pasting one in. */
export function JsonPanel({ state, send }: PanelProps) {
  const text = state.jsonText || JSON.stringify(toCanonicalJson(state.layout), null, 2);
  return (
    <form
      className="space-y-2"
      onSubmit={(e) => {
        e.preventDefault();
        send({ type: 'importJson', text });
      }}
    >
      <textarea
        aria-label="Layout JSON"
        rows={16}
        className="textarea textarea-bordered w-full font-mono text-xs"
        value={text}
        onChange={(e) => send({ type: 'jsonChange', text: e.target.value })}
      />
      {state.jsonError && <p className="text-error text-xs">{state.jsonError}</p>}
      <div className="flex gap-2">
        <button
          type="button"
          className="btn btn-sm"
          onClick={() => send({ type: 'jsonChange', text: '' })}
        >
          Refresh from editor
        </button>
        <button type="submit" className="btn btn-sm btn-primary">
          Load into editor
        </button>
      </div>
    </form>
  );
}

/** Save: name the layout and store it. */
export function SavePanel({ layout, onSave }: { layout: Layout; onSave: (name: string) => void }) {
  const [name, setName] = useState(layout.name);
  useEffect(() => setName(layout.name), [layout.name]);

  return (
    <form
      className="space-y-2"
      onSubmit={(e) => {
        e.preventDefault();
        onSave(name);
      }}
    >
      <label className="form-control">
        <span className="label-text text-xs">Name</span>
        <input
          aria-label="Layout name"
          className="input input-sm input-bordered"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
      </label>
      <button type="submit" className="btn btn-sm btn-primary">
        Save to library
      </button>
      <p className="text-[11px] opacity-60">
        Saved layouts appear in the library and are referenced in links as saved:&lt;id&gt;.
      </p>
    </form>
  );
}
